# Generated by Django 2.2 on 2019-04-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIRST',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FIRST', models.CharField(blank=True, max_length=1024, null=True)),
                ('RAJ2000', models.DecimalField(blank=True, decimal_places=15, help_text='Right Ascension in decimal degree units', max_digits=19, null=True)),
                ('DEJ2000', models.DecimalField(blank=True, decimal_places=15, help_text='Declination in decimal degree units', max_digits=19, null=True)),
                ('Fint', models.DecimalField(blank=True, decimal_places=15, help_text='mJy, Integrated flux density (akin to intensity) in radio astronomer units', max_digits=19, null=True)),
                ('c1', models.CharField(blank=True, help_text='s=star; g=galaxy; or blank', max_length=10, null=True)),
            ],
            options={
                'ordering': ['-ID'],
            },
        ),
    ]
