# Generated by Django 2.2 on 2019-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='DEJ2000',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Declination in decimal degree units', max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='first',
            name='Fint',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='mJy, Integrated flux density (akin to intensity) in radio astronomer units', max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='first',
            name='RAJ2000',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Right Ascension in decimal degree units', max_digits=27, null=True),
        ),
    ]
